# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{titi}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mrflip"]
  s.date = %q{2010-04-18}
  s.description = %q{Facade adapting apis to activity streams spec}
  s.email = %q{flip@infochimps.org}
  s.extra_rdoc_files = [
    "LICENSE.textile",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.textile",
     "README.textile",
     "Rakefile",
     "VERSION",
     "examples/twitter.rb",
     "lib/titi.rb",
     "lib/titi/adaptor.rb",
     "lib/titi/fetcher.rb",
     "lib/titi/fetcher/json.rb",
     "lib/titi/ignore/hpricot.rb",
     "lib/titi/ignore/html_parser.rb",
     "lib/titi/ignore/matcher.rb",
     "lib/titi/ignore/parse_tree.rb",
     "lib/titi/provider.rb",
     "lib/titi/provider/README.textile",
     "lib/titi/provider/activity_streams.rb",
     "lib/titi/provider/activity_streams/README.textile",
     "lib/titi/provider/activity_streams/activity_streams_struct.rb",
     "lib/titi/provider/activity_streams/actor.rb",
     "lib/titi/provider/activity_streams/address.rb",
     "lib/titi/provider/activity_streams/entry.rb",
     "lib/titi/provider/activity_streams/feed.rb",
     "lib/titi/provider/activity_streams/feed.xml.erb",
     "lib/titi/provider/activity_streams/link.rb",
     "lib/titi/provider/activity_streams/obj.rb",
     "lib/titi/provider/ameba/.gitignore",
     "lib/titi/provider/avatars_united/.gitignore",
     "lib/titi/provider/baidu/.gitignore",
     "lib/titi/provider/bebo/.gitignore",
     "lib/titi/provider/blipfm/.gitignore",
     "lib/titi/provider/blippr/.gitignore",
     "lib/titi/provider/bliptv/.gitignore",
     "lib/titi/provider/blogger/.gitignore",
     "lib/titi/provider/brightkite/.gitignore",
     "lib/titi/provider/buzznet/.gitignore",
     "lib/titi/provider/cinchcast/.gitignore",
     "lib/titi/provider/corkd/.gitignore",
     "lib/titi/provider/daily_motion/.gitignore",
     "lib/titi/provider/delicious/.gitignore",
     "lib/titi/provider/delicious/README.textile",
     "lib/titi/provider/deviant_art/.gitignore",
     "lib/titi/provider/digg/.gitignore",
     "lib/titi/provider/diigo/.gitignore",
     "lib/titi/provider/douban/.gitignore",
     "lib/titi/provider/flickr/.gitignore",
     "lib/titi/provider/flickr/README.textile",
     "lib/titi/provider/flickr/models.rb",
     "lib/titi/provider/flixster/.gitignore",
     "lib/titi/provider/fotolog/.gitignore",
     "lib/titi/provider/friendfeed/.gitignore",
     "lib/titi/provider/friendster/.gitignore",
     "lib/titi/provider/funny_or_die/.gitignore",
     "lib/titi/provider/gamer_dna/.gitignore",
     "lib/titi/provider/gather/.gitignore",
     "lib/titi/provider/generic_feed.rb",
     "lib/titi/provider/generic_feed/.gitignore",
     "lib/titi/provider/goodreads/.gitignore",
     "lib/titi/provider/google_reader/.gitignore",
     "lib/titi/provider/gowalla/README.textile",
     "lib/titi/provider/hatena/.gitignore",
     "lib/titi/provider/hi5/.gitignore",
     "lib/titi/provider/hulu/.gitignore",
     "lib/titi/provider/hyves/.gitignore",
     "lib/titi/provider/identica/.gitignore",
     "lib/titi/provider/ilike/.gitignore",
     "lib/titi/provider/jaiku/.gitignore",
     "lib/titi/provider/joost/.gitignore",
     "lib/titi/provider/lastfm/.gitignore",
     "lib/titi/provider/librarything/.gitignore",
     "lib/titi/provider/list_of_providers.rb",
     "lib/titi/provider/livejournal/.gitignore",
     "lib/titi/provider/meneame/.gitignore",
     "lib/titi/provider/metacafe/.gitignore",
     "lib/titi/provider/mixx/.gitignore",
     "lib/titi/provider/moby_picture/.gitignore",
     "lib/titi/provider/multiply/.gitignore",
     "lib/titi/provider/netlog/.gitignore",
     "lib/titi/provider/newsvine/.gitignore",
     "lib/titi/provider/pandora/.gitignore",
     "lib/titi/provider/photobucket/.gitignore",
     "lib/titi/provider/photocase/.gitignore",
     "lib/titi/provider/picasa/.gitignore",
     "lib/titi/provider/plancast/README.textile",
     "lib/titi/provider/plurk/.gitignore",
     "lib/titi/provider/posterous/.gitignore",
     "lib/titi/provider/propeller/.gitignore",
     "lib/titi/provider/qik/.gitignore",
     "lib/titi/provider/qype/.gitignore",
     "lib/titi/provider/raptr/.gitignore",
     "lib/titi/provider/readernaut/.gitignore",
     "lib/titi/provider/reddit/.gitignore",
     "lib/titi/provider/revver/.gitignore",
     "lib/titi/provider/skyrock/.gitignore",
     "lib/titi/provider/slideshare/.gitignore",
     "lib/titi/provider/smotri/.gitignore",
     "lib/titi/provider/smugmug/.gitignore",
     "lib/titi/provider/stumbleupon/.gitignore",
     "lib/titi/provider/tripit.rb",
     "lib/titi/provider/tumblr/.gitignore",
     "lib/titi/provider/tumblr/README.textile",
     "lib/titi/provider/twelve_seconds/.gitignore",
     "lib/titi/provider/twine/.gitignore",
     "lib/titi/provider/twitter.rb",
     "lib/titi/provider/twitter/.gitignore",
     "lib/titi/provider/twitter/README.textile",
     "lib/titi/provider/twitter/models.rb",
     "lib/titi/provider/twitter/rss_feed.rb",
     "lib/titi/provider/vimeo/.gitignore",
     "lib/titi/provider/visualizeus/.gitignore",
     "lib/titi/provider/weather_gov/README.textile",
     "lib/titi/provider/wordpress/.gitignore",
     "lib/titi/provider/xanga/.gitignore",
     "lib/titi/provider/yelp/.gitignore",
     "lib/titi/provider/youtube/README.textile",
     "lib/titi/provider/zooomr/.gitignore",
     "notes/jeweler-gen.sh",
     "spec/data/provider/ameba/.gitignore",
     "spec/data/provider/avatars_united/.gitignore",
     "spec/data/provider/baidu/.gitignore",
     "spec/data/provider/bebo/.gitignore",
     "spec/data/provider/blipfm/.gitignore",
     "spec/data/provider/blippr/.gitignore",
     "spec/data/provider/bliptv/.gitignore",
     "spec/data/provider/blogger/.gitignore",
     "spec/data/provider/brightkite/.gitignore",
     "spec/data/provider/buzznet/.gitignore",
     "spec/data/provider/cinchcast/.gitignore",
     "spec/data/provider/corkd/.gitignore",
     "spec/data/provider/daily_motion/.gitignore",
     "spec/data/provider/delicious/.gitignore",
     "spec/data/provider/delicious/delicious_bookmarks-activity_streams.xml",
     "spec/data/provider/delicious/delicious_bookmarks-raw_feed.xml",
     "spec/data/provider/deviant_art/.gitignore",
     "spec/data/provider/digg/.gitignore",
     "spec/data/provider/diigo/.gitignore",
     "spec/data/provider/douban/.gitignore",
     "spec/data/provider/flickr/.gitignore",
     "spec/data/provider/flickr/flickr_favorites-activity_streams.xml",
     "spec/data/provider/flickr/flickr_favorites-raw_rss.xml",
     "spec/data/provider/flixster/.gitignore",
     "spec/data/provider/fotolog/.gitignore",
     "spec/data/provider/friendfeed/.gitignore",
     "spec/data/provider/friendster/.gitignore",
     "spec/data/provider/funny_or_die/.gitignore",
     "spec/data/provider/gamer_dna/.gitignore",
     "spec/data/provider/gather/.gitignore",
     "spec/data/provider/generic_feed/.gitignore",
     "spec/data/provider/goodreads/.gitignore",
     "spec/data/provider/google_reader/.gitignore",
     "spec/data/provider/hatena/.gitignore",
     "spec/data/provider/hi5/.gitignore",
     "spec/data/provider/hulu/.gitignore",
     "spec/data/provider/hyves/.gitignore",
     "spec/data/provider/identica/.gitignore",
     "spec/data/provider/identica/identica_statuses-raw_feed.xml",
     "spec/data/provider/ilike/.gitignore",
     "spec/data/provider/jaiku/.gitignore",
     "spec/data/provider/joost/.gitignore",
     "spec/data/provider/lastfm/.gitignore",
     "spec/data/provider/librarything/.gitignore",
     "spec/data/provider/livejournal/.gitignore",
     "spec/data/provider/meneame/.gitignore",
     "spec/data/provider/metacafe/.gitignore",
     "spec/data/provider/mixx/.gitignore",
     "spec/data/provider/moby_picture/.gitignore",
     "spec/data/provider/multiply/.gitignore",
     "spec/data/provider/netlog/.gitignore",
     "spec/data/provider/newsvine/.gitignore",
     "spec/data/provider/pandora/.gitignore",
     "spec/data/provider/photobucket/.gitignore",
     "spec/data/provider/photocase/.gitignore",
     "spec/data/provider/picasa/.gitignore",
     "spec/data/provider/plurk/.gitignore",
     "spec/data/provider/posterous/.gitignore",
     "spec/data/provider/propeller/.gitignore",
     "spec/data/provider/qik/.gitignore",
     "spec/data/provider/qype/.gitignore",
     "spec/data/provider/raptr/.gitignore",
     "spec/data/provider/readernaut/.gitignore",
     "spec/data/provider/reddit/.gitignore",
     "spec/data/provider/revver/.gitignore",
     "spec/data/provider/skyrock/.gitignore",
     "spec/data/provider/slideshare/.gitignore",
     "spec/data/provider/smotri/.gitignore",
     "spec/data/provider/smugmug/.gitignore",
     "spec/data/provider/stumbleupon/.gitignore",
     "spec/data/provider/tumblr/.gitignore",
     "spec/data/provider/tumblr/tumblr_posts-raw_feed.xml",
     "spec/data/provider/twelve_seconds/.gitignore",
     "spec/data/provider/twine/.gitignore",
     "spec/data/provider/twitter/.gitignore",
     "spec/data/provider/twitter/twitter-api_user_timeline-activity_streams.xml",
     "spec/data/provider/twitter/twitter-api_user_timeline-raw_json.json",
     "spec/data/provider/twitter/twitter_rss_user_timeline-activity_streams.xml",
     "spec/data/provider/twitter/twitter_rss_user_timeline-raw_feed.xml",
     "spec/data/provider/vimeo/.gitignore",
     "spec/data/provider/visualizeus/.gitignore",
     "spec/data/provider/wordpress/.gitignore",
     "spec/data/provider/xanga/.gitignore",
     "spec/data/provider/yelp/.gitignore",
     "spec/data/provider/youtube/youtube_videos-activity_streams.xml",
     "spec/data/provider/youtube/youtube_videos-raw_feed.xml",
     "spec/data/provider/zooomr/.gitignore",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/compare_to_standard_example.rb",
     "spec/titi_spec.rb",
     "titi.gemspec"
  ]
  s.homepage = %q{http://github.com/mrflip/titi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Emit and consume Activity Streams from a wide variety of sources}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/support/compare_to_standard_example.rb",
     "spec/titi_spec.rb",
     "examples/twitter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<restclient>, [">= 0.0.0"])
      s.add_runtime_dependency(%q<wukong>, [">= 0.0.0"])
      s.add_runtime_dependency(%q<active_support>, [">= 0.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<restclient>, [">= 0.0.0"])
      s.add_dependency(%q<wukong>, [">= 0.0.0"])
      s.add_dependency(%q<active_support>, [">= 0.0.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<restclient>, [">= 0.0.0"])
    s.add_dependency(%q<wukong>, [">= 0.0.0"])
    s.add_dependency(%q<active_support>, [">= 0.0.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

